leftnav:
- identifier: 63beabe5-d756-6e9e-8558-700a2cf378f6
  name: Syllabus
  pageRef: /courses/21w-780-communicating-in-technical-organizations-fall-2001/sections/syllabus
  weight: 10
- identifier: 289d5967-ddf1-e3d5-3c94-224464db3019
  name: Readings
  pageRef: /courses/21w-780-communicating-in-technical-organizations-fall-2001/sections/readings
  weight: 20
- identifier: 97ff4825-8dc4-7fbe-9de9-b00714d004ec
  name: Calendar
  pageRef: /courses/21w-780-communicating-in-technical-organizations-fall-2001/sections/calendar
  weight: 30
- identifier: 44b2b094-d95f-4afe-cfd6-f071489a85a9
  name: Assignments
  pageRef: /courses/21w-780-communicating-in-technical-organizations-fall-2001/sections/assignments
  weight: 40
